#!/usr/bin/env bash

username="$BLENDER_USERNAME"
password="$BLENDER_PASSWORD"
hostname="$BLENDER_HOSTNAME"
args=

if ! which curl > /dev/null 2>&1; then
	echo "Missing dependency: curl" >&2
	exit 1
fi

if [ "$1" = "on" -o "$1" = "1" ]; then
	args="--data 'blender=1'"
elif [ "$1" = "off" -o "$1" = "0" ]; then
	args="--data 'blender=0'"
elif [ "$1" = "status" ]; then
	args=
else
	echo "Usage: $(basename $0) [on|off|status]" >&2
	exit 1
fi

if [ -z "$username" -o -z "$password" -o -z "$hostname" ]; then
	echo "Error: A required variable is unset!" >&2
	echo "Edit '$(basename $0)' to remedy this, or set a BLENDER_ variable" >&2
	exit 1
fi

echo "Status:"
curl --user "${username}":"${password}" $args http://$hostname:8192
